### PR TITLE
New link for Jen Vasic/active transit meetup

### PR DESCRIPTION
**Pull request by hjroaf**
It's still doing this thing of thinking many lines have changed, but in reality have only changed the one field.

### CODE REVIEW

**Comment by pnijjar** [comment]
No, this is more serious. Your update changed many of the date formats from YYYY-MM-dd to dd/MM/YYYY format (eg 2018-08-01 to 01/08/2018). That is no good and will break things. This may be a setting in your spreadsheet program. 

Also I feel that the old link (although ugly) is probably better than the new one because it is more accessible to people not on Facebook. If you really want the Facebook link instead then I will merge it, but you have to fix the format of the file first.

**Comment by pnijjar** [comment]
I don't know whether it is better to close this pull request and have you submit a different one or to leave this open. I will leave it open for now and hope nobody commits it.

**Comment by hjroaf** [comment]
Oh no! Ok, just let me know if there's anything I can do. Will make sure to
check the date format for strangeness in future updates.

**Comment by pnijjar** [comment]
In Numbers, it looks like you can change cell formatting on a sheet-by-sheet basis, but not globally unless you change your system settings on the Mac (!): 

Sheet by sheet: https://support.apple.com/kb/PH17075?locale=en_US&viewlocale=en_US
(So select the columns for beginning and end date, and then disable the date formatting)

Overall: https://apple.stackexchange.com/questions/75855/how-to-set-default-number-formatting-in-numbers
(which is probably not something you want to do)

**Comment by hjroaf** [comment]
I actually made the change/submitted the pull request from my work machine
which is Windows, so my Excel settings were the issue. If you feel the blog
link is best, just go ahead and close this request. In future I'll just use
my mac because that didn't cause as many issues and I don't want to spend
time mucking around in Excel.

**Comment by hjroaf** [comment]
Added another event, but looks like it got added to this open pull request...

**Comment by pnijjar** [comment]
Grr. 

Okay. I took the event you added and manually stuck it in the spreadsheet, then committed it. 

From your end, I think you need to go to the Branches menu and delete the branch that is the pull request. Then you should be able to make new pull requests that won't pull in the bad stuff. I am going to close this pull request, but I don't think your desktop client will get the hint. 

I think this process will get smoother as we get more used to it. Hang in there!

**Pull request closed without merging**
